apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radanalytics-spark-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radanalytics-spark-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          value: anz-ml
        image: quay.io/radanalyticsio/spark-operator:1.1.0
        imagePullPolicy: Always
        name: spark-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: spark-crd-operator
      serviceAccountName: spark-crd-operator
      terminationGracePeriodSeconds: 5
