apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.radanalytics.io
spec:
  conversion:
    strategy: None
  group: radanalytics.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}