apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    operators.coreos.com/radanalytics-spark.ml-workshop: ""
  name: sparkoperator.v1.1.0-spark-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sparkoperator.v1.1.0-spark-operator-role
subjects:
- kind: ServiceAccount
  name: spark-operator