apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - modeldb-deployment.yaml
  - modeldb-route.yaml
  - modeldb-secret.yaml
  - modeldb-service.yaml
  - modeldb-statefullset.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "modeldb"
