apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-create-secret
spec:
  template:
    metadata:
      name: airflow-create-secret
    spec:
      restartPolicy: OnFailure
      containers:
        - name: airflow-create-secret-container
          image: 'registry.redhat.io/openshift4/ose-cli:v4.7'
          imagePullPolicy: IfNotPresent

          command:
            - /bin/sh
            - -c
            - "echo | openssl s_client -showcerts -servername openshift.default.svc.cluster.local -connect openshift.default.svc.cluster.local:443 > /tmp/cert.txt && sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' /tmp/cert.txt > /tmp/ca.crt && oc create secret airflow-auth-cert --from-file=ca.crt=/tmp/ca.crt -n ml-workshop"



            