
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-aflow-airflow-scheduler
spec:
  template:
    spec:
      containers:
        - name: git-sync
          image: 'k8s.gcr.io/git-sync/git-sync:v3.2.2'
        - name: airflow-scheduler
          image: 'quay.io/ml-aml-workshop/airflow-custom:2.0.0.scheduler'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-aflow-airflow-web
spec:
  template:
    spec:
      containers:
        - name: git-sync
          image: 'k8s.gcr.io/git-sync/git-sync:v3.2.2'
        - name: airflow-web
          image: 'quay.io/ml-aml-workshop/airflow-custom:2.1.6.web'

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-postgresql
spec:
  template:
    spec:
      containers:
        - name: app-aflow-postgresql
          image: 'registry.redhat.io/rhel8/postgresql-10:1-154'

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-redis-master
  namespace: "ml-workshop"
spec:
  template:
    spec:
      containers:
        - name: redis
          image: 'registry.redhat.io/rhel8/redis-6:1-18'

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-airflow-worker
spec:
  template:
    spec:
      containers:
        - name: git-sync
          image: 'k8s.gcr.io/git-sync/git-sync:v3.2.2'
        - name: airflow-worker
          image: 'quay.io/ml-aml-workshop/airflow-custom:2.0.0.worker'
