apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  # - statefulset-db.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - deployment-scheduler.yaml
  - statefulset-redis.yaml
# namespace: anz-ml
# configurations:
#   - params.yaml
# configMapGenerator:
#   - name: airflow2-config
#     envs:
#       - params.env
# vars:
#   - name: AIRFLOW_GIT_SYNC_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_GIT_SYNC_IMAGE
#   - name: AIRFLOW_SCHEDULER_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_SCHEDULER_IMAGE
#   - name: AIRFLOW_WEB_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_WEB_IMAGE
#   - name: AIRFLOW_POSTGRESQL_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_POSTGRESQL_IMAGE
#   - name: AIRFLOW_REDIS_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_REDIS_IMAGE
#   - name: AIRFLOW_WORKER_IMAGE
#     objref:
#       name: airflow2-config
#       kind: ConfigMap
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.AIRFLOW_WORKER_IMAGE
