apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-postgresql
  # namespace: "anz-ml"
spec:
  template:
    spec:
      containers:
        - name: app-aflow-postgresql
          image: 'quay.io/internaldatahub/postgresql-96-centos7:9.6'
          # image: 'registry.redhat.io/rhel8/postgresql-10:1-154'