

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-aflow-postgresql
spec:
  template:
    spec:
      containers:
        - name: app-aflow-postgresql
          image: 'registry.redhat.io/rhel8/postgresql-10:1-154'

