apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-db
spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000630000
      containers:
      - image: quay.io/internaldatahub/postgresql-96-centos7:9.6
        name: postgresql
