apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
  - jupyterhub-singleuser-profiles-sizes-configmap.yaml


commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: jupyterhub