apiVersion: v1
kind: Secret
metadata:
  name: trino-catalog
stringData:
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://hive-metastore:9083
    hive.s3.endpoint=$(s3_endpoint_url_prefix)$(s3_endpoint_url)
    hive.s3.signer-type=S3SignerType
    hive.s3.path-style-access=true
    hive.s3.staging-directory=/tmp
    hive.s3.ssl.enabled=false
    hive.s3.sse.enabled=false
    hive.allow-drop-table=true
    hive.parquet.use-column-names=true
    hive.recursive-directories=true
  customerchurn.properties: |
    connector.name=kafka
    kafka.nodes=odh-message-bus-kafka-bootstrap:9092
    kafka.table-names=data
    kafka.hide-internal-columns=false
  data.json: |
    {
    "tableName": "data",
    "topicName": "data",
    "dataFormat": "json",
    "message": {
        "dataFormat":"json",
        "fields": [
            {
                "name": "customerID",
                "mapping": "customerID",
                "type": "INTEGER"
            },
            {
                "name": "PhoneService",
                "mapping": "PhoneService",
                "type": "VARCHAR"
            },
            {
                "name": "MultipleLines",
                "mapping": "MultipleLines",
                "type": "VARCHAR"
            },
            {
                "name": "InternetService",
                "mapping": "InternetService",
                "type": "VARCHAR"
            },
            {
                "name": "OnlineSecurity",
                "mapping": "OnlineSecurity",
                "type": "VARCHAR"
            },
            {
                "name": "OnlineBackup",
                "mapping": "OnlineBackup",
                "type": "VARCHAR"
            },
            {
                "name": "DeviceProtection",
                "mapping": "DeviceProtection",
                "type": "VARCHAR"
            },
            {
                "name": "TechSupport",
                "mapping": "TechSupport",
                "type": "VARCHAR"
            },
            {
                "name": "StreamingTV",
                "mapping": "StreamingTV",
                "type": "VARCHAR"
            },
            {
                "name": "StreamingMovies",
                "mapping": "StreamingMovies",
                "type": "VARCHAR"
            },
            {
                "name": "Contract",
                "mapping": "Contract",
                "type": "VARCHAR"
            },
            {
                "name": "PaperlessBilling",
                "mapping": "PaperlessBilling",
                "type": "VARCHAR"
            },
            {
                "name": "MonthlyCharges",
                "mapping": "MonthlyCharges",
                "type": "VARCHAR"
            },
            {
                "name": "TotalCharges",
                "mapping": "TotalCharges",
                "type": "DOUBLE"
            },
            {
                "name": "Churn",
                "mapping": "Churn",
                "type": "VARCHAR"
            }
        ]
    }
    }
  jmx.properties: |
    connector.name=jmx
