apiVersion: apps/v1
kind: Deployment
metadata:
  name: thriftserver-db
spec:
  template:
    spec:
      containers:
        - name: postgres-exporter
          image: $(THRIFT_DB_EXPORTER_IMAGE)
        - name: postgresql
          image: $(THRIFT_DB_IMAGE)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thriftserver
spec:
  template:
    spec:
      containers:
        - name: thriftserver
          image: $(THRIFT_SERVER_IMAGE)