apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - airflow-base.yaml
  - airflow-cluster.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "airflow"
