# Source: kafka-populator/templates/kafka_populator_job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kafkadump-ml-workshop-telco
  labels:
    application: kafkadump-ml-workshop
spec:
  template:
    metadata:
      name: kafkadump-ml-workshop-telco
    spec:
      restartPolicy: Never
      initContainers:
        - name: waitkafka
          image: 'registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest'
          command: ['sh', '-c', "until nslookup odh-message-bus-kafka-bootstrap.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for kafka service; sleep 2; done"]
      containers:
        - name: kafka-dump-ml-workshop-telco
          image: 'quay.io/ml-aml-workshop/kafka-churn-populator:0.0.2'
          imagePullPolicy: Always
          env:
            - name: CHURN_FILE
              value: '/tmp/Customer-Churn_P2.csv'
            - name: KAFKA_SERVERS
              value: odh-message-bus-kafka-bootstrap:9092
            - name: KAFKA_TOPIC
              value: datatelco

          command:
            - /bin/sh
            - -c
            - python /opt/load-csv.py
