apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-topic-fsi.yaml
  - kafka-topic-telco.yaml
  - kafkapopulator-job-fsi.yaml
  - kafkapopulator-job-telco.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "kakfa-populator"
