apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
spec:
  template:
    metadata:
      annotations:        
        containerImage: $(SELDON_CORE_IMAGE)
    spec:
      containers:
      - image: $(SELDON_CORE_IMAGE)
        name: manager
        