apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mlflow-postgesql-statefulset.yaml
  - mlflow-dc.yaml
  - mlflow-route.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "mlflow"
