apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    olm.owner: seldon-operator.v1.7.0
    olm.owner.kind: ClusterServiceVersion
    operators.coreos.com/seldon-operator-certified.ml-workshop: ""
  name: seldon-controller-manager
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: seldon-operator.v1.7.0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: seldon
      app.kubernetes.io/instance: seldon1
      app.kubernetes.io/name: seldon
      app.kubernetes.io/version: v0.5
      control-plane: seldon-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alm-examples: |-
          [
            {
              "apiVersion": "machinelearning.seldon.io/v1",
              "kind": "SeldonDeployment",
              "metadata": {
                "labels": {
                  "app": "seldon",
                  "app.kubernetes.io/instance": "seldon1",
                  "app.kubernetes.io/name": "seldon",
                  "app.kubernetes.io/version": "v0.5"
                },
                "name": "seldon-model"
              },
              "spec": {
                "name": "test-deployment",
                "predictors": [
                  {
                    "componentSpecs": [
                      {
                        "spec": {
                          "containers": [
                            {
                              "image": "seldonio/mock_classifier:1.6.0",
                              "name": "classifier"
                            }
                          ]
                        }
                      }
                    ],
                    "graph": {
                      "children": [],
                      "name": "classifier",
                      "type": "MODEL"
                    },
                    "name": "example",
                    "replicas": 1
                  }
                ]
              },
              "status": {}
            }
          ]
        capabilities: Seamless Upgrades
        categories: AI/Machine Learning
        certified: "false"
        containerImage: registry.connect.redhat.com/seldonio/seldon-core-operator@sha256:d50e4585f1f212b3fd5aa4200ccb2e2260b44cf17ed4d0fc89bfa61cf1969b9b
        description: The Seldon operator for management, monitoring and operations of machine learning systems through the Seldon Engine. Once installed, the Seldon Operator provides multiple functions which facilitate the productisation, monitoring and maintenance of machine learning systems at scale.
        olm.operatorGroup: opendatahub
        # olm.operatorNamespace: ml-workshop
        # olm.targetNamespaces: ml-workshop
        operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"machinelearning.seldon.io","kind":"SeldonDeployment","version":"v1"}},{"type":"olm.gvk","value":{"group":"machinelearning.seldon.io","kind":"SeldonDeployment","version":"v1alpha2"}},{"type":"olm.gvk","value":{"group":"machinelearning.seldon.io","kind":"SeldonDeployment","version":"v1alpha3"}},{"type":"olm.package","value":{"packageName":"seldon-operator-certified","version":"1.7.0"}}]}'
        operators.operatorframework.io/builder: operator-sdk-v1.2.0
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
        repository: https://github.com/SeldonIO/seldon-core
        sidecar.istio.io/inject: "false"
        support: Clive Cox
      creationTimestamp: null
      labels:
        app: seldon
        app.kubernetes.io/instance: seldon1
        app.kubernetes.io/name: seldon
        app.kubernetes.io/version: v0.5
        control-plane: seldon-controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --webhook-port=8443
        - --create-resources=$(MANAGER_CREATE_RESOURCES)
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: RELATED_IMAGE_EXECUTOR
          value: registry.connect.redhat.com/seldonio/seldon-core-executor@sha256:2831ca7ae5a1451df2b8ebe26784a9b8e2ef80834350a76512b9f6790c6a0e55
        - name: RELATED_IMAGE_ENGINE
          value: registry.connect.redhat.com/seldonio/seldon-engine@sha256:eac00afa854e5e03f367c5b052b631b20246f0b068f92669f04facc1d6d88ee0
        - name: RELATED_IMAGE_STORAGE_INITIALIZER
          value: registry.connect.redhat.com/seldonio/storage-initializer@sha256:3bd2c461a522b8de3a350cac259b6188c092fd032f0b38ad446fc5be4a3d2d34
        - name: RELATED_IMAGE_SKLEARNSERVER
          value: registry.connect.redhat.com/seldonio/sklearnserver@sha256:88d126455b150291cbb3772f67b4f35a88bb54b15ff7c879022f77fb051615ad
        - name: RELATED_IMAGE_XGBOOSTSERVER
          value: registry.connect.redhat.com/seldonio/xgboostserver@sha256:85a572a03e2c0ce1a7fb10c622f73c65d717a6e05c1ee00f5148b25774394f0b
        - name: RELATED_IMAGE_MLFLOWSERVER
          value: registry.connect.redhat.com/seldonio/mlflowserver@sha256:05cc0ecb43052aedb27954f478c059c08a8f133df71f96a39ab7eeabd0329dcd
        - name: RELATED_IMAGE_TFPROXY
          value: registry.connect.redhat.com/seldonio/tfproxy@sha256:e6ed51c45aaf1ca07ae4aaa7c2174795823dd92d7cc1073757ce671fb12abcbb
        - name: RELATED_IMAGE_TENSORFLOW
          value: registry.connect.redhat.com/seldonio/tensorflow-serving@sha256:1dc53edc5c8d1b151782f8386c0770d0358c6397eaf42ec55ebd18f331c5ef9e
        - name: RELATED_IMAGE_EXPLAINER
          value: registry.connect.redhat.com/seldonio/alibiexplainer@sha256:a8f17861182f9611d50af0db2c93b9ddb6077b8b1919867ca92afe368886ffcd
        - name: RELATED_IMAGE_MOCK_CLASSIFIER
          value: registry.connect.redhat.com/seldonio/mock-classifier@sha256:35952ee4778151cd5fc69929b94e82e2dcb0ad111ffb76f7b406a2e8cc461700
        - name: MANAGER_CREATE_RESOURCES
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONTROLLER_ID
        - name: AMBASSADOR_ENABLED
          value: "true"
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "false"
        - name: ENGINE_CONTAINER_IMAGE_AND_VERSION
          value: docker.io/seldonio/engine:1.7.0
        - name: ENGINE_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: ENGINE_CONTAINER_USER
        - name: ENGINE_LOG_MESSAGES_EXTERNALLY
          value: "false"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_DEFAULT_ENV_SECRET_REF_NAME
        - name: PREDICTIVE_UNIT_METRICS_PORT_NAME
          value: metrics
        - name: ENGINE_SERVER_GRPC_PORT
          value: "5001"
        - name: ENGINE_SERVER_PORT
          value: "8000"
        - name: ENGINE_PROMETHEUS_PATH
          value: /prometheus
        - name: ISTIO_ENABLED
          value: "false"
        - name: KEDA_ENABLED
          value: "false"
        - name: ISTIO_GATEWAY
          value: istio-system/seldon-gateway
        - name: ISTIO_TLS_MODE
        - name: USE_EXECUTOR
          value: "true"
        - name: EXECUTOR_CONTAINER_IMAGE_AND_VERSION
          value: seldonio/seldon-core-executor:1.7.0
        - name: EXECUTOR_CONTAINER_IMAGE_PULL_POLICY
          value: IfNotPresent
        - name: EXECUTOR_PROMETHEUS_PATH
          value: /prometheus
        - name: EXECUTOR_SERVER_PORT
          value: "8000"
        - name: EXECUTOR_CONTAINER_USER
        - name: EXECUTOR_CONTAINER_SERVICE_ACCOUNT_NAME
          value: default
        - name: EXECUTOR_SERVER_METRICS_PORT_NAME
          value: metrics
        - name: EXECUTOR_REQUEST_LOGGER_DEFAULT_ENDPOINT
          value: http://default-broker
        - name: DEFAULT_USER_ID
        - name: EXECUTOR_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: EXECUTOR_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: EXECUTOR_DEFAULT_MEMORY_LIMIT
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_REQUEST
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_REQUEST
          value: 512Mi
        - name: ENGINE_DEFAULT_CPU_LIMIT
          value: "0.5"
        - name: ENGINE_DEFAULT_MEMORY_LIMIT
          value: 512Mi
        image: registry.connect.redhat.com/seldonio/seldon-core-operator@sha256:d50e4585f1f212b3fd5aa4200ccb2e2260b44cf17ed4d0fc89bfa61cf1969b9b
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 8443
          name: webhook-server
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: seldon-manager
      serviceAccountName: seldon-manager
      terminationGracePeriodSeconds: 10