kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ml-workshop-elyra-seldon-alibi
  labels:
    opendatahub.io/notebook-image: 'true'
  annotations:
    opendatahub.io/notebook-image-name: MLWorkShop Notebook Image Drift and Outlier
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/ml-aml-workshop/elyra:0.0.2'
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Local
