apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elyra-imagestream.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "custom-images"
