apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  template:
    spec:
      initContainers:
        - name: waitkafka
          image: 'registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest'
      containers:
        - name: oauth-proxy
          image: 'openshift/oauth-proxy:latest'
        - name: mlflow-deployment
          image: 'quay.io/ml-aml-workshop/mlflow:0.0.2'