apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
spec:
  template:
    spec:
      containers:
      - image: $(RADANALYTICS_SPARK_OPERATOR_IMAGE)
        name: spark-operator
        