apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: ml-jenkins
spec:
  master:
    containers:
      - image: >-
          quay.io/redhat-developer/origin-jenkins@sha256:a8e94991bd42290c51310ad1d34554f1d1604813a9f15f8acf96e18f71ff65c7
        name: jenkins