apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hive
    hive: metastore
  name: hive-metastore
spec:
  template:
    spec:
      containers:
        - env:
            - name: HIVE_LOGLEVEL
              value: "DEBUG"