apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      containers:
      - name: metastore
        image: $(TRINO_HIVE_IMAGE)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
spec:
  template:
    spec:
      containers:
        - name: trino-coordinator
          image: $(TRINO_IMAGE)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-db
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: $(TRINO_DB_IMAGE)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
spec:
  template:
    spec:
      containers:
        - name: trino-worker
          image: $(TRINO_IMAGE)