apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      containers:
      - name: metastore
        image: quay.io/cloudservices/ubi-hive:2.3.3-002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
spec:
  template:
    spec:
      containers:
        - name: trino-coordinator
          image: $(trino_image)

---
apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: postgresql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
spec:
  template:
    spec:
      containers:
        - name: trino-worker
          image: $(trino_image)