apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jupyterhub-db
spec:
  template:
    metadata:
    spec:
      containers:
      - image: registry.redhat.io/rhel8/postgresql-96
        name: postgresql
