apiVersion: apps/v1
kind: Deployment
metadata:
  name: supersetdb
spec:
  template:
    spec:
      containers:
      - name: postgresql
        image: quay.io/internaldatahub/postgresql-96-centos7:9.6