apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secrets.yaml
  - service.yaml
  - service-accounts.yaml
  - route.yaml
  - deployment-web.yaml
  - deployment-worker.yaml
  - deployment-scheduler.yaml
  - statefulset-db.yaml
  - statefulset-redis.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "airflow2"
