apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-mysql
spec:
  template:
    spec:
      containers:
        - name: mysqld-exporter
          image: $(HUE_MYSQL_EXPORTER_IMAGE)
        - name: mysql
          image: $(HUE_MYSQL_IMAGE)