apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue
spec:
  template:
    spec:
      initContainers:
        - name: db-init
          image: $(HUE_IMAGE)
      containers:
        - name: hue
          image: $(HUE_IMAGE)